import java.sql.*;

public class DbmsVersion
{
    public static void main(String argvs[])
    {
        Connection connection = null;
        String qry = null;
        Statement stmt = null;
        ResultSet rset = null;
        try
        {
            String url = System.getenv("DB_URL");
            if (url != null) {
                connection = DriverManager.getConnection(url); 
                stmt = connection.createStatement(); 
                qry = "SELECT dbmsinfo('_version') from iidbconstants";
                rset = stmt.executeQuery(qry); 
                while(rset.next() ) 
                {
                    String version = rset.getString("col1").trim();
                    System.out.print("\n   DBMS version: " + version + "\n");
                }
            } else {
                System.out.println("\nPlease set environment variable DB_URL and try again");
                System.exit(-1);
            }
        }
        catch(SQLException sqlex)   // Errors generated by JDBC
        {
            System.out.println("Error Code: " + sqlex.getErrorCode());
            System.out.println("SQL State: " + sqlex.getSQLState());
            System.out.println("Error Messsage: " + sqlex.getMessage());
            Throwable t = sqlex.getCause();
        }
        catch(Exception ex)   // Other errors
        {
            System.out.println("Error Messsage: " + ex.getMessage());
            ex.printStackTrace();
        }
    }
}

