CREATE TABLE airline (al_name NVARCHAR(60), al_ccode NCHAR(2)) \g

INSERT INTO airline (al_name, al_ccode) VALUES 
('Air Japan Company Ltd.', 'JP'), 
('British Airways P.L.C.', 'GB'), 
('Continental Air Lines, Inc.', 'US'), 
('Finnair Oyj', 'FI'), 
('Martinair Holland N.V.', 'NL'), 
('Air Canada', 'CA'), 
('Air France', 'FR'), 
('Air Berlin GmbH & Co. Luftverkehrs KG', 'DE'), 
('Jet Airways (India) Limited', 'IN'), 
('Korean Air Lines Co. Ltd.', 'KR'), 
('Canjet Airlines', 'CA'), 
('PAN AIR Lineas Aereas, S.A.', 'ES'), 
('American Airlines', 'US'), 
('Air-India Limited', 'IN'), 
('Spanair, S.A.', 'ES'), 
('Air Nippon Co. Ltd.', 'JP'), 
('Russian Sky Airlines JSC', 'RU'), 
('Indian Airlines Corporation', 'IN'), 
('Transair Sweden AB', 'SE'), 
('Delta Air Lines, Inc.', 'US'), 
('Japan Airlines International Co. Ltd.', 'JP'), 
('Virgin Atlantic Airways Limited', 'GB'), 
('Régional Compagnie Aérienne Européenne', 'FR'), 
('Air Finland Ltd.', 'FI'), 
('South African Airways', 'ZA'), 
('United Airlines, Inc.', 'US'), 
('Swedjet Airways AB', 'SE'), 
('SAS Braathens AS', 'NO'), 
('Eurowings AG', 'DE'), 
('Scandinavian Airlines System (SAS)', 'SE'), 
('Southwest Airlines Co.', 'US'), 
('Australian Airlines Ltd.', 'AU'), 
('Qantas Airways Ltd.', 'AU'), 
('Air Zambezi', 'ZW'), 
('Air Orient', 'FR'), 
('Aeroflot Russian Airlines', 'RU'), 
('Deutsche Lufthansa AG', 'DE'), 
('Iberia - Lineas Aereas de Espana', 'ES'), 
('KLM Royal Dutch Airlines (Koninklijke Luchtvaart Maatschappi', 'NL'), 
('Ryanair Ltd.', 'IE'), 
('British Midland Airways Ltd. d/b/a bmi', 'GB'), 
('Aer Lingus Limited', 'IE') \g

COMMIT \g
